server:
  port: 9500
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/<Database>?autoReconnect=true&useSSL=false
    username: <Username>
    password: <Password>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true