server:
  port: 9000
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript
    min-response-size: 2048
spring:
  profiles:
    active: production

---
spring:
  profiles: dev
  thymeleaf:
    cache: false
  resources:
    cache:
      period: 0s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/<Database>?autoReconnect=true&useSSL=false
    username: <Username>
    password: <Password>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

---
spring:
  profiles: production
  thymeleaf:
    cache: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/<Database>?autoReconnect=true&useSSL=false
    username: <Username>
    password: <Password>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true